### PR TITLE
New Pull

### PR DESCRIPTION
**Pull request by Skrilltrax**

### CODE REVIEW

**Comment by anuragk47** [comment]
Pull request to merge our own changes?

**Comment by Skrilltrax** [comment]
Sorry , Im Kinda A New To This So , I Did This By Mistake

**Comment by crutchcorn** [comment]
No worries! :) We all make mistakes here and there, and Git can be very
challenging to use. Would you like help?

**Comment by Skrilltrax** [comment]
Thanks Corbin , Can You Please Help Me , So That I Can Merge Your New
Commits To My Forked Repo. Also , Since I Have Changed The Readme.md It Is
Showing Conflicts , Is There Any Way , I Can Stop README.md From Changing ,
While I Include Your Changes... ???

P.S :Thanks For Being Helpful

**Comment by anuragk47** [comment]
No need to worry Aditya, that's alright. I am myself quite new and make
silly mistakes at times. You need to use patch to merge selective changes
from commits.

**Comment by Skrilltrax** [comment]
Thanks For All The Help Guys , I Read The Github's Document To Sync A Fork
And Will Be Able To Do It.

**Pull request closed without merging**
